version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "8083:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
